### ISSUE TITLE
CSS margin-top 溢出问题

### ISSUE THREAD

**Issue by MaMaFish** [MaMaFish/Note#40]
```html
<html>
  <style>
    .wrapper {
      background-color: red;
      height: 200px;
      width: 200px;
    }
    .inner {
      width: 100px;
      height: 100px;
      background-color: blue;
      margin-top: 50px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="inner"></div>
    </div>
  </body>
</html>
```
![Screen Shot 2021-01-07 at 17 04 15](https://user-images.githubusercontent.com/15073228/103873454-c74a7300-510a-11eb-8c83-3d7bf94d5919.png)

## 第一种方式 CSS:
```css
    .wrapper {
      background-color: red;
      height: 200px;
      width: 200px;
    }
    .wrapper::before {
      content: '';
      display: table;
    }
    .inner {
      width: 100px;
      height: 100px;
      background-color: blue;
      margin-top: 50px;
    }
```
效果如下：
![Screen Shot 2021-01-07 at 17 09 41](https://user-images.githubusercontent.com/15073228/103874060-aafb0600-510b-11eb-9331-8190238daf8e.png)

## 第二种方式 CSS:
```css
    .wrapper {
      background-color: red;
      height: 200px;
      width: 200px;
    }
    .wrapper::before {
      content: '.';
      display: block;
      height: 0;
      visibility: hidden;
    }
    .inner {
      width: 100px;
      height: 100px;
      background-color: blue;
      margin-top: 50px;
    }
```
